name: Push and Commit Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Commit changes
        run: |
          git config --global user.email "lalitha.challa@cbts.com"
          git config --global user.name "lalitha-CBTS"
          git add .
          git commit -m "Automated commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GithubActions }}
