name: Push and Commit Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: set up git
        run: |
          git config --global user.email "lalitha.challa@cbts.com"
          git config --global user.name "lalitha-CBTS"
          
      - name: push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN}}
          branch: develop
